name: Create sprite sheets

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build
      run: python generate.py

    - name: Upload to S3
      uses: dijkstraj/s3-upload-github-action@master
      with:
        args: --acl public-read
      env:
        FOLDER: "./output"
        INCLUDE: "*.png"
        S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        S3_KEY: sprites/
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
